### ISSUE TITLE
GitHub Actions Template for Deploying FilamentPHP (Laravel)

### ISSUE THREAD

**Issue by vincent-lahaye** [getOtterWise/bash-uploader#1]
Hi Lasse,

I wanted to share the GitHub Action template that deploys my FilamentPHP (v3.2) app. This template:

- Runs tests
- Triggers a deployment to Laravel Forge
- Submits test and type coverage to Otterapp

I want to maintain full control over the uploader.sh file, as it could potentially be exploited by an attacker to leak my app's data. Therefore, I've forked this repository to analyze any changes made to the uploader.sh file before integrating it into my workflow.

Since type coverage calculation can be time-consuming, I'm triggering the deployment before it.

```
name: Run tests
 
on: [push]
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
    
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install JS dependencies
        run: yarn install
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Yarn build
        run: yarn build
       
      - name: Execute tests
        run: vendor/bin/pest --coverage-clover=build/logs/clover.xml

      - name: Trigger forge deployment
        run: curl -X GET https://forge.laravel.com/servers/[...]
        
      - name: Calculate type coverage
        run: vendor/bin/pest --type-coverage --type-coverage-json=pest-coverage.json

      - name: Upload Coverage
        env:
          OTTERWISE_TOKEN: ${{ secrets.OTTERWISE_TOKEN }}
        run: bash <(curl -s https://raw.githubusercontent.com/my-org/my-otterwise-bash-uploader-fork/main/uploader.sh) --type-coverage-file=pest-coverage.json

```

Feel free to reuse, share, and provide feedback! :)

**Comment by LasseRafn** [comment]
Hi Vincent! Digging the idea of forking, very smart approach. I will definitively recommend that in the docs as well!

Really appreciate, I will give proper attributions when sharing! 🙏🏻 Can I include it in an example repository?

**Comment by vincent-lahaye** [comment]
Cheers! 😊 Absolutely, feel free to include it in your example repository.

**Comment by pelmered** [comment]
I would suggest that you add the uploader as a custom GitHub Action. 
So you could use something like:

```
      - name: Upload coverage
        uses: otterwise/uploader@v1
        with:
          token: ${{ secrets.OTTERWISE_TOKEN }}
          file: my/clover.xml
          type-coverage-file: my/pest-coverage.json
```
